springdoc:
  packagesToScan: net.flexberry
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
    use-root-path: true
spring:
  application:
    name: SpringBootBackend
  kafka:
    bootstrap-servers: broker:29092
    client-id: spring-boot-backend-producer
    template:
      default-topic: spring-boot-backend-topic