version: '3'
services:
    springboot-postgres-db:
        image: springbootsample/postgres
        volumes:
        - DB:/var/lib/pgsql/data/
        ports:
        - 5432:5432

    springboot-backend:
        image: springbootsample/backend
        build:
            context: .
        depends_on:
            - springboot-postgres-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://springboot-postgres-db:5432/appdb
            - SPRING_DATASOURCE_USERNAME=flexberryuser
            - SPRING_DATASOURCE_PASSWORD=jhv
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - "8082:8080"
            
    springboot-gateway:
        image: springbootsample/gateway
        ports:
            - "8081:8760"

volumes:
  DB:
