version: '3'

services:
    springboot-postgres-db:
        image: springbootsample/postgres
        volumes:
                - DB:/var/lib/pgsql/data/
        ports:
                - 5432:5432

    springboot-backend:
        image: springbootsample/backend
        build:
            context: .
        depends_on:
            - springboot-postgres-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://springboot-postgres-db:5432/appdb
            - SPRING_DATASOURCE_USERNAME=flexberryuser
            - SPRING_DATASOURCE_PASSWORD=jhv
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            
    springboot-gateway:
        image: springbootsample/gateway
        ports:
            - "8081:8760"

    springboot-elasticsearch:
        image: springbootsample/elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - 'xpack.security.enabled=false'
            - 'discovery.type=single-node'
            - 'bootstrap.memory_lock=true'
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
    
    loki:
        image: springbootsample/loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - LOKIDB:/loki
            
    grafana:
        image: springbootsample/grafana
        ports:
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: usr123
   
    zookeeper:
        image: springbootsample/zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    broker:
        image: springbootsample/broker
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  DB:
  LOKIDB: