apiVersion: 1
datasources:
  - name: Loki-Spring-Logs
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100 #host - container name
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
  - name: Elasticsearch-comment
    uid: dd56f93c-d54a-411f-b0ec-70b6b8d0b7ca
    orgId: 1
    type: elasticsearch
    typeName: Elasticsearch
    access: proxy
    url: 'http://springboot-elasticsearch:9200'
    user: ''
    database: comment
    basicAuth: false
    isDefault: false
    jsonData:
      includeFrozen: false
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: 5
      timeField: 'commentdate'
    readOnly: false