name: Java Spring Boot build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11.16
        env:
          POSTGRES_DB: appdb        
          POSTGRES_PASSWORD: jhv
          POSTGRES_USER: flexberryuser
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file src/SpringBootBackend/pom.xml
